export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'

export const SHOW_STUDENT_RESULT = 'SHOW_STUDENT_RESULT'


export const SHOW_STUDENT_QUIZ = 'SHOW_STUDENT_QUIZ'


export const SHOW_TEACHER_RESULT = 'SHOW_TEACHER_RESULT'
export const ALL_TEACHER_RESULT = 'ALL_TEACHER_RESULT'
export const SHOW_TEACHER_QUIZ = 'SHOW_TEACHER_QUIZ'
export const GET_TEACHER_RESPONSE = 'GET_TEACHER_RESPONSE'


export const EDIT_QUIZ = 'EDIT_QUIZ'

export const SUBMIT = 'SUBMIT'

export const SUBMIT_FAILED = 'SUBMIT_FAILED'
