export const SHOW_STUDENT_RESULT = 'SHOW_STUDENT_RESULT'
export const SHOW_TEACHER_RESULT = 'SHOW_TEACHER_RESULT'
export const GET_TEACHER_RESPONSE = 'GET_TEACHER_RESPONSE'
export const EDIT_QUIZ = 'EDIT_QUIZ'

export const SUBMIT = 'SUBMIT'

export const SUBMIT_FAILED = 'SUBMIT_FAILED'
